name: sql_transformer
description: Dart package for parsing and using SQL files.
version: 0.0.2
homepage: https://github.com/worknaut/dart_sql_tranformer
documentation: https://pub.dev/documentation/sql_transformer/latest/

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
