name: sql_transformer
description: Dart package with useful transformers for SQL queries. Splitting SQL statements from a single file, and replacing variables in them.
version: 0.0.4
homepage: https://github.com/worknaut/dart_sql_tranformer
documentation: https://pub.dev/documentation/sql_transformer/latest/

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
